<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Añadir producto Carrito Amazon</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0e4a3a3a-d1f7-43e8-a8a4-c1b8dba457cb</testSuiteGuid>
   <testCaseLink>
      <guid>dec6fbff-c18f-4f52-ac38-deb46b84b7d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Añadir Producto al Carrito/Añadir Producto por Seccion Categorias</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bf3234d-dba3-491b-a3c2-cb870313bac1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0358eba0-5f8d-40a3-aeaa-e06d44c5af8f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a868523-7279-4b9c-adf1-2587e02e2a24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Añadir Producto al Carrito/Añadir Producto por Barra de Busqueda</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9e4c4dc-f15c-45b8-a8ac-0ca6153037d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83d20bfd-ad94-4de1-9fd8-b22eeadf9fe6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
